name: kantin_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0-198.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#d4e4ed"
  
